### ISSUE TITLE
SSLClient.cpp unreachable code bug

### ISSUE THREAD

**Issue by BigJim** [david-maw/StreamSSL#11]
In [https://github.com/david-maw/StreamSSL/blob/master/StreamClient/SSLClient.cpp](url) line #847 you will see this line:
`if (pbMessage != NULL && cbMessage != 0)`

If you study the code a few lines above it, you will realize this case will never be true since "pbMessage" is assigned NULL, and "cbMessage" is set to zero also.

Not a breaking problem, seems to work well enough with this small bug regardless.

Also for quick reference:
[https://docs.microsoft.com/en-us/windows/desktop/SecAuthN/shutting-down-an-schannel-connection](url)

= = = = = = = = = = = 
On a personal side note, thanks for for your excellent work.
The Windows SSPI API is an obscure, unintuitive,  overly complex, and poorly documented mess.
Probably most people give up in frustration and restore to use either Windows OpenSSL or CURL.
Your working SSPI SSL/TLS is the single best working example that can be found on the entire internet!

**Comment by david-maw** [comment]
Yep, that sure smells like a bug to me, thanks for spotting it (and thanks for the kind words), I'm guessing the SCHANNEL (SSL) connection is not shut down at all, just closed when the underlying TCP connection closes. I'll take a proper look at it when I have a bit more time. As you say it doesn't look like it causes a problem, but it seems like there's some code missing.

**Comment by david-maw** [comment]
It looks like there was a chunk of code missing from CSSLServer::Disconnect and CSSLClient::Disconnect, basically the calls on  AcceptSecurityContext / InitializeSecurityContext which generate the "shutdown" message. Adding that code handled the shutdown and also explains why the unreachable code is actually needed.
