### ISSUE TITLE
The members ActualSocket and  m_hStopEvent of CActiveSock should be protected or public

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#20]
The members ActualSocket and m_hStopEvent of class CActiveSock should be protected or public so that a derived class has access to it - same as in MFC's CAsyncSocket. So it would be possible to write a class derived from CActiveSock that handles the WM_SOCKET_NOTIFY messages
 FD_READ, FD_WRITE, FD_CLOSE, .. and calls overridable callbacks OnSend, OnReceive, OnConnect, ... similar to CAsyncSocket.

**Comment by Thomas-Haase** [comment]
Yes, that sounds very plausible.
