### ISSUE TITLE
CertFindFromIssuerList should use user store, not machine store?

### ISSUE THREAD

**Issue by Thomas-Haase** [david-maw/StreamSSL#21]
I'm using your client part in my application, and my client application has to support _client certificates_. Unfortunately, I'm in trouble with this, and I can't get it running via my `SelectClientCertificate` callback function, which is still very close to the example you have provided in StreamClient.cpp.

I believe, that `CertFindFromIssuerList` should look in the **user store**, not in the machine store as you have implemented. On the other side, this is the only function where you have not provided this `boolean fUserStore` parameter, you might have a good reason for this, which I currently do not understand so far.

I want to let you know, how I have tested (I did double checks with Windows 10 Edge Browser, same approach has helped a lot to get the server certificate running):
1. I have imported my client certificates into the **machine store**: Edge **does not find** this client certificates. Your code via `CertFindFromIssuerList` **does not find** this certificates. Thus I deleted the certificates in this store.
2. I have imported my client certificates into the **user store**: Edge **does find** this client certificates. Your code via `CertFindFromIssuerList` **does not find** this certificates.
3. I have imported my client certificates into the **user store**: Edge **does find** this client certificates. Your code via modified `CertFindFromIssuerList` with  `boolean fUserStore` parameter, **does find** this certificates. Fine. Works.

I would be very interested in your opinion about this.

**Comment by david-maw** [comment]
No good reason that I can think of offhand Thomas, indeed there IS good reason to all the per-user store to be selected as you have noted. I’ll take a proper look at the weekend but I really cannot think of a reason offhand.

My direct mail address is david@maw.name if you need it; I’m happy to help, just busy.

Thanks for all your contributions.

David

From: Thomas-Haase
Sent: Thursday, July 11, 2019 5:06 AM
To: david-maw/StreamSSL
Cc: Subscribed
Subject: [david-maw/StreamSSL] CertFindFromIssuerList should use user store,not machine store? (#21)

I'm using your client part in my application, and my client application has to support client certificates. Unfortunately, I'm in trouble with this, and I can't get it running via my SelectClientCertificate callback function, which is still very close to the example you have provided in StreamClient.cpp.
I believe, that CertFindFromIssuerList should look in the user store, not in the machine store as you have implemented. On the other side, this is the only function where you have not provided this boolean fUserStore parameter, you might have a good reason for this, which I currently do not understand so far.
I want to let you know, how I have tested (I did double checks with Edge, same approach has helped a lot to get the server certificate running):
1. I have imported my client certificates into the machine store: Windows 10 Edge does not find this client certificates. Your code via CertFindFromIssuerList does not find this certificates. Thus I deleted the certificates in this store.
2. I have imported my client certificates into the user store: Windows 10 Edge does find this client certificates. Your code via CertFindFromIssuerList does not find this certificates.
3. I have imported my client certificates into the user store: Windows 10 Edge does find this client certificates. Your code via modified CertFindFromIssuerList with boolean fUserStore parameter, does find this certificates. Fine. Works.
I would be very interested in your opinion about this.

**Comment by Thomas-Haase** [comment]
Thanks for your answer. and thanks for all your work. I'm happy if I can contribute minor stuff to make it even better. Waiting for the weekend...

**Comment by david-maw** [comment]
You probably already noticed, but I updated CertFindFromIssuerList and that CertFindServerCertificateByName so both now accept an optional fUserStore parameter. I defaulted it to false for backward compatibility and consistency with the existing functions.

David

From: David Maw
Sent: Thursday, July 11, 2019 7:31 AM
Subject: RE: [david-maw/StreamSSL] CertFindFromIssuerList should use userstore,not machine store? (#21)

No good reason that I can think of offhand Thomas, indeed there IS good reason to all the per-user store to be selected as you have noted. I’ll take a proper look at the weekend but I really cannot think of a reason offhand.

My direct mail address is david@maw.name if you need it; I’m happy to help, just busy.

Thanks for all your contributions.

David

From: Thomas-Haase
Sent: Thursday, July 11, 2019 5:06 AM
To: david-maw/StreamSSL
Cc: Subscribed
Subject: [david-maw/StreamSSL] CertFindFromIssuerList should use user store,not machine store? (#21)

I'm using your client part in my application, and my client application has to support client certificates. Unfortunately, I'm in trouble with this, and I can't get it running via my SelectClientCertificate callback function, which is still very close to the example you have provided in StreamClient.cpp.
I believe, that CertFindFromIssuerList should look in the user store, not in the machine store as you have implemented. On the other side, this is the only function where you have not provided this boolean fUserStore parameter, you might have a good reason for this, which I currently do not understand so far.
I want to let you know, how I have tested (I did double checks with Edge, same approach has helped a lot to get the server certificate running):
1. I have imported my client certificates into the machine store: Windows 10 Edge does not find this client certificates. Your code via CertFindFromIssuerList does not find this certificates. Thus I deleted the certificates in this store.
2. I have imported my client certificates into the user store: Windows 10 Edge does find this client certificates. Your code via CertFindFromIssuerList does not find this certificates.
3. I have imported my client certificates into the user store: Windows 10 Edge does find this client certificates. Your code via modified CertFindFromIssuerList with boolean fUserStore parameter, does find this certificates. Fine. Works.
I would be very interested in your opinion about this.
