### ISSUE TITLE
stdafx.h was renamed to pch.h since Visual Studio 2017 also a targetver.h and a framework.h was added.

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#24]
see https://docs.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=vs-2017
and https://docs.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=vs-2019

**Comment by david-maw** [comment]
It is indeed renamed, and new projects will use the new name. Other than consistency with new defaults does renaming it have other advantages?

**Comment by Blonder** [comment]
I think it is only to be less confusing and a more consistent name.
