### ISSUE TITLE
Im confused with WSAResetEvent calls.

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#25]
Hello,
is this correct that in CActiveSock::RecvPartial WSAResetEvent with parameter hEvents[1] (m_hStopEvent) is called and in CActiveSock::SendPartial WSAResetEvent  with parameter read_event
ALso the return values are not checked, acording to the documentation:
  If the WSAResetEvent function succeeds, the return value is TRUE. 
  If the function fails, the return   value is FALSE. To get extended error information, call WSAGetLastError.
So in our case LastError = WSAGetLastError(); should be set and return SOCKET_ERROR; should be called in both functions (CActiveSock::RecvPartial and CActiveSock::SendPartial)

**Comment by david-maw** [comment]
No, you’re not confused, it’s a mistake. That code is in a path that rarely gets used because Send operations almost always finish immediately, still, it’s wrong, so I fixed it.

**Comment by Blonder** [comment]
In revision 36ecf6267b69b2ad458bfd3e2c3eb5706911df09 you fixed it in CPassiveSock::SendPartial but not in CActiveSock::RecvPartial were os.hEvent = hEvents[1] = m_hStopEvent,
I would be more failsafe if you would initialize WSAEVENT hEvents in all places the same way.
