### ISSUE TITLE
Bug in CActiveSock::Disconnect

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#59]
is:
`else if (!(WSACloseEvent(read_event) || WSACloseEvent(write_event) || CloseAndInvalidateSocket() || WSACleanup()))`

must be:
`else if (!(WSACloseEvent(read_event) && WSACloseEvent(write_event) && CloseAndInvalidateSocket() && 0 == WSACleanup()))`

**Comment by david-maw** [comment]
You're right, don't know what I was smoking.... Fixed.
