### ISSUE TITLE
WinErrorMsg when does if (theMsg.empty()) case occure?

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#71]

**Comment by david-maw** [comment]
Only if the caller passes an undefined error - and the WinErrorMsg code is broken for that case anyway, it should be:
```
		auto len = FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM...
		theMsg.resize(len);
		if (theMsg.empty()) ...
```
To make it fail as an example:
`	wcout << L"WinErrorMsg: " << WinErrorMsg(ERROR_HANDLE_DISK_FULL+1) << endl;
`
I'll check in a fix for the bug.
